version: '3.8'
services:

  #PHP Service
  app:
    build: dev-docker
    container_name: musicmgmt-app
    working_dir: /app
    environment:
      - PHP_MEMORY_LIMIT=-1
      - WEB_DOCUMENT_ROOT=/app/public
    ports:
      - "8080:80"
      - "443:443"
      - "5173:5173"
    volumes:
      - .:/app
    tty: true

  #MySQL Service
  db:
    image: mysql:8.0.32
    container_name: musicmgmt-db
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: musicmgmt
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
